name: "Genera JSON a partir de los ficheros de objetivos"
on:
  push:
    paths:
      - proyectos/objetivos*.md
      - .github/workflows/commit-json.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/jj/raku-github-actions
    steps:
      - name: Checkout this
        uses: actions/checkout@v2
      - name: Cache para las distros instaladas
        uses: actions/cache@v2
        id: meta6
        with:
          path: ~/.raku/
          key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
      - name: Instala m√≥dulos Raku
        if: steps.meta6.outputs.cache-hit != 'true'
        run: |
          zef update
          echo $RAKULIB
          zef search File::Directory::Tree
          zef upgrade --force File::Directory::Tree
          zef install .
      - name: Genera JSON
        run: raku -Ilib scripts/iv-objetivos.raku > data/objetivos.json
      - name: Sube resultados
        run: |
          if [[ $(git status -s) ]]; then
              git config --global user.email "jjmerelo@gmail.com"
              git config --global user.name "IVDataBot"
              git commit -am "Actualiza JSON"
              git push
          else
              echo "üüè No ha habido cambios"
          fi
